### ISSUE TITLE
Improve installation guide and build guide 

### ISSUE THREAD

**Issue by mirandapedro** [abracm/display-latam#10]
Ideally, we'd have both the usual technical documentation, but also a very basic how-to guide (if possible, even a video), teaching how to build the project, so that it is as accessible as possible for communities, regardless of their level of technical expertise.

**Comment by mirandapedro** [comment]
Should we recommend a specific version of an ESP32/arduino as a default for the project or can we make the project and code version neutral?

**Comment by alexmaasswca** [comment]
I think we should stick with the C3because the acrylic case is designed for that, the boards seem to be roughly all about a few dollars on aliexpress for me so I don't see any major price differences there.

I think we should try to get the C3 working first and perfected and then add in support for different boards.

**Comment by mirandapedro** [comment]
Just to note the specific version of the ESP32 C3 mini we used in our first batch of display is the ESP32-C3FH4. I don't believe any of the differences between the versions of the ESP32 C3 mini impact our project, but it's worth noting for future testing and documentation.

**Comment by soyrandom1** [comment]
Code should work with most arduino and esp versions. 
In some cases used pins might change depending on the board used, but it's extremely easy to modify in code. 
In my case I've used the esp32 wroom da and other delegate used a regular Arduino UNO board.

**Comment by mirandapedro** [comment]
@soyrandom1 do you believe the code is ready for an Alpha release (after merging your PR)?

If so, the only thing holding us back would be the documentation/tutorial.

My hope was to have an alpha version ready as soon as possible to make the first prototype available to interested communities. Also, a first release might also attract the interest of additional contributors.

**Comment by soyrandom1** [comment]
Solved #19
