### ISSUE TITLE
Libraries missing

### ISSUE THREAD

**Issue by alexmaasswca** [abracm/display-latam#12]
I had a lot of trouble installing arduino libraries with the jayanth github. I think it is problematic to just simply say "download this library from this other github" because the libraries can change, this actually led to an issue with jayanth's project because he had to reupload an older version of the libraries so it would work for other people.

This is the same case here, for example running the program gets me this error that simply says that the Adafruit.h library is not there so I think it would be best to have a UsedLibraries folder on the github here and place every library needed in that folder, so it'll always work and be very easy to download multiple libraries without having to worry about the libraries being updated.

I'll be down to write a guide on how to install the whole thing once the libraries are posted in a folder here.

**Comment by soyrandom1** [comment]
Uploaded all libraries [here](https://github.com/abracm/display-latam/blob/main/Libs.zip)
